"use client";

import { ExternalLink } from "lucide-react";
import Link from "next/link";
import { DashboardShell } from "~/components/dashboard/dashboard-shell";
import { Button } from "~/components/ui/button";
import { Card } from "~/components/ui/card";

// Sample invoice data - in a real app, this would come from your backend
const invoices = [
  {
    id: "INV-2023-001",
    date: "Jun 1, 2023",
    amount: "$9.00",
    status: "Paid",
    stripeId: "in_1234567890",
  },
  {
    id: "INV-2023-002",
    date: "May 1, 2023",
    amount: "$9.00",
    status: "Paid",
    stripeId: "in_0987654321",
  },
  {
    id: "INV-2023-003",
    date: "Apr 1, 2023",
    amount: "$9.00",
    status: "Paid",
    stripeId: "in_1122334455",
  },
];

export default function BillingPage() {
  // Stripe customer portal URL would be generated by your backend
  const stripePortalUrl = "https://billing.stripe.com/p/login/test";

  return (
    <DashboardShell>
      <div className="space-y-6">
        <h2 className="text-2xl font-medium">Billing & Invoices</h2>

        <Card className="p-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-lg font-medium">Current Plan</h3>
              <p className="text-sm text-muted-foreground">
                You are currently on the Starter plan.
              </p>
            </div>
            <Button asChild>
              <a
                href={stripePortalUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2"
              >
                <span>Manage Subscription</span>
                <ExternalLink className="h-4 w-4" />
              </a>
            </Button>
          </div>

          <div className="mt-6">
            <div className="rounded-md bg-muted p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium">Starter Plan</p>
                  <p className="text-sm text-muted-foreground">$9/month</p>
                </div>
                <div className="text-sm">
                  Next billing date: Jul 1, 2023
                </div>
              </div>
              <ul className="mt-4 space-y-1 text-sm">
                <li className="flex items-center gap-2">
                  <svg className="h-4 w-4 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  <span>1,000,000 tokens per month</span>
                </li>
                <li className="flex items-center gap-2">
                  <svg className="h-4 w-4 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  <span>5,000 API requests per month</span>
                </li>
                <li className="flex items-center gap-2">
                  <svg className="h-4 w-4 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  <span>Email support</span>
                </li>
              </ul>
            </div>
          </div>
        </Card>

        <Card className="p-6">
          <h3 className="text-lg font-medium">Recent Invoices</h3>
          <div className="mt-4">
            <div className="rounded-md border">
              <div className="divide-y">
                {invoices.map((invoice, index) => (
                  <div
                    key={index}
                    className="flex items-center justify-between p-4"
                  >
                    <div>
                      <a
                        href={`${stripePortalUrl}#/invoices/${invoice.stripeId}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="font-medium text-primary hover:underline"
                      >
                        {invoice.id}
                      </a>
                      <p className="text-sm text-muted-foreground">{invoice.date}</p>
                    </div>
                    <div>
                      <p className="font-medium text-right">{invoice.amount}</p>
                      <p className="text-sm text-muted-foreground text-right">{invoice.status}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className="mt-4 text-center">
              <Button variant="outline" asChild>
                <a
                  href={`${stripePortalUrl}#/invoices`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center justify-center gap-2"
                >
                  <span>View All Invoices</span>
                  <ExternalLink className="h-4 w-4" />
                </a>
              </Button>
            </div>
          </div>
        </Card>

        <div className="text-center text-sm text-muted-foreground">
          For billing questions, please
          {" "}
          <Link href="/dashboard/contact" className="text-primary hover:underline">contact support</Link>
          .
        </div>
      </div>
    </DashboardShell>
  );
}
